name: news_app
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev. Remove if you plan to publish.
publish_to: "none"

# Application version and build number.
version: 1.0.0+1

# SDK and environment version.
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies for your app.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  http: ^1.2.2
  shimmer: ^3.0.0
  flutter_tts: ^4.2.0
  lottie: ^3.1.3
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  intl: ^0.20.2

# Development-only dependencies for testing and linting.
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#34374B"
  image: "assets/newsziee.png"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/newsziee.png"

flutter:
  uses-material-design: true

  # Asset files used in the app.
  assets:
    - assets/animations/Animation.json
    - assets/images/user_avatar.jpg
    # Add other assets like images or fonts here as needed.
    # Example:
    # - assets/images/
    # - assets/fonts/

  # Font configuration example (uncomment and configure as needed).
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700
